apiVersion: v1
kind: Namespace
metadata:
  name: stage
  labels:
    namespace: stage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stage-front-back
  namespace: stage
  labels:
    app: stage-front-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stage-front-back
  template:
    metadata:
      labels:
        app: stage-front-back
    spec:
      containers:
      - name: backend
        image: zaglodin/13.1-backend:stage
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: backend-env
          mountPath: /app/.env
          subPath: .env
          readOnly: true
      - name: frontend
        image: zaglodin/13.1-frontend:stage
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: frontend-env
          mountPath: /app/.env
          subPath: .env
          readOnly: true
      volumes:
      - name: backend-env
        configMap:
          name: stage-config
          items:
            - key: backend.env
              path: .env
      - name: frontend-env
        configMap:
          name: stage-config
          items:
            - key: frontend.env
              path: .env
---
apiVersion: v1
kind: Service
metadata:
  name: stage-front-back-svc
  namespace: stage
  labels:
    app: stage-front-back
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: stage-front-back
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stage-front-back
  namespace: stage
data:
  backend.env: |-
    DATABASE_URL=postgres://postgres:postgres@task1-db.stage:5432/news
  frontend.env: |-
    BASE_URL=http://localhost:9000